#!/usr/bin/env node
/**
 * Generate HANDOFF.md for exe.dev deployment
 *
 * Creates a context document that gives remote Claude enough
 * information to continue development meaningfully.
 *
 * Usage:
 *   import { generateHandoff } from './generate-handoff.js';
 *
 *   const content = generateHandoff({
 *     appDescription: 'A todo app with real-time sync',
 *     files: ['index.html'],
 *     originalPrompt: 'Build me a todo app',
 *     decisions: '- Used Fireproof for persistence\n- Added dark mode toggle',
 *     nextSteps: 'User mentioned wanting to add categories'
 *   });
 */

/**
 * Generate a context handoff document from session context.
 * This gives remote Claude enough context to continue development.
 *
 * @param {Object} options - Handoff options
 * @param {string} [options.appDescription] - What was built
 * @param {string[]} [options.files] - List of files included
 * @param {string} [options.originalPrompt] - User's original request
 * @param {string} [options.decisions] - Key decisions made during development
 * @param {string} [options.nextSteps] - What to do next
 * @param {string} [options.vmName] - Name of the exe.dev VM
 * @returns {string} HANDOFF.md content
 */
export function generateHandoff(options = {}) {
  const {
    appDescription = 'A Vibes app',
    files = ['index.html'],
    originalPrompt = 'Build an app',
    decisions = '- Standard Vibes architecture with Fireproof database',
    nextSteps = 'Continue development based on user requests.',
    vmName = 'app'
  } = options;

  const fileList = Array.isArray(files)
    ? files.map(f => `- \`${f}\``).join('\n')
    : `- \`${files}\``;

  const handoff = `# Development Handoff

This document was generated during deployment to exe.dev. It provides context
for continuing development on this VM.

## What Was Built

${appDescription}

## Files Included

${fileList}

## User's Original Request

> ${originalPrompt}

## Key Decisions Made

${decisions}

## What To Do Next

${nextSteps}

## Technical Context

**Stack:**
- Framework: React (via Babel transpilation, no build step)
- Database: Fireproof (local-first, syncs automatically)
- Styling: Tailwind CSS via CDN
- Runtime: Runs directly in browser

**Architecture:**
- Single \`index.html\` file with embedded JSX
- \`<script type="text/babel">\` for React components
- Import map for CDN dependencies (esm.sh)
- No server-side logic - pure static hosting

**Common Commands:**
\`\`\`bash
# View the app
open https://${vmName}.exe.xyz

# Edit the app
nano /var/www/html/index.html

# Check nginx status
sudo systemctl status nginx

# View nginx logs
sudo tail -f /var/log/nginx/access.log
\`\`\`

---
*Generated by vibes-skill on ${new Date().toISOString().split('T')[0]}*
`;

  return handoff;
}

/**
 * Extract context from environment variables set by the vibes skill.
 * Falls back to sensible defaults if not available.
 *
 * @returns {Object} Context object for generateHandoff
 */
export function extractContextFromEnv() {
  return {
    appDescription: process.env.VIBES_APP_DESCRIPTION || 'A Vibes app',
    originalPrompt: process.env.VIBES_ORIGINAL_PROMPT || 'Build an app',
    decisions: process.env.VIBES_DECISIONS || '- Standard Vibes architecture with Fireproof database',
    nextSteps: process.env.VIBES_NEXT_STEPS || 'Continue development based on user requests.',
    vmName: process.env.VIBES_VM_NAME || 'app'
  };
}

// CLI usage: node generate-handoff.js [--output path]
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const outputIndex = args.indexOf('--output');
  const outputPath = outputIndex !== -1 ? args[outputIndex + 1] : null;

  const context = extractContextFromEnv();
  context.files = ['index.html']; // Default for CLI usage

  const content = generateHandoff(context);

  if (outputPath) {
    const { writeFileSync } = await import('fs');
    writeFileSync(outputPath, content);
    console.log(`HANDOFF.md written to ${outputPath}`);
  } else {
    console.log(content);
  }
}
