/**
 * Unit tests for generate-handoff.js
 *
 * Tests the HANDOFF.md generation for exe.dev deployments.
 * The handoff document provides context for remote Claude to continue development.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { generateHandoff, extractContextFromEnv } from '../../generate-handoff.js';

describe('generateHandoff', () => {
  describe('with default options', () => {
    it('generates valid markdown', () => {
      const result = generateHandoff();

      expect(result).toContain('# Development Handoff');
      expect(result).toContain('## What Was Built');
      expect(result).toContain('## Files Included');
      expect(result).toContain('## Technical Context');
    });

    it('uses default app description', () => {
      const result = generateHandoff();

      expect(result).toContain('A Vibes app');
    });

    it('uses default files list', () => {
      const result = generateHandoff();

      expect(result).toContain('`index.html`');
    });

    it('uses default original prompt', () => {
      const result = generateHandoff();

      expect(result).toContain('> Build an app');
    });

    it('includes technical stack info', () => {
      const result = generateHandoff();

      expect(result).toContain('React');
      expect(result).toContain('Fireproof');
      expect(result).toContain('Tailwind CSS');
    });

    it('includes VM commands with default name', () => {
      const result = generateHandoff();

      expect(result).toContain('app.exe.xyz');
      expect(result).toContain('/var/www/html');
    });
  });

  describe('with custom options', () => {
    it('uses custom app description', () => {
      const result = generateHandoff({
        appDescription: 'A task management app with real-time collaboration'
      });

      expect(result).toContain('A task management app with real-time collaboration');
      expect(result).not.toContain('A Vibes app');
    });

    it('uses custom files list', () => {
      const result = generateHandoff({
        files: ['index.html', 'styles.css', 'app.js']
      });

      expect(result).toContain('`index.html`');
      expect(result).toContain('`styles.css`');
      expect(result).toContain('`app.js`');
    });

    it('handles single file as string', () => {
      const result = generateHandoff({
        files: 'custom.html'
      });

      expect(result).toContain('`custom.html`');
    });

    it('uses custom original prompt', () => {
      const result = generateHandoff({
        originalPrompt: 'Create a kanban board with drag and drop'
      });

      expect(result).toContain('> Create a kanban board with drag and drop');
    });

    it('uses custom decisions', () => {
      const result = generateHandoff({
        decisions: '- Used react-beautiful-dnd for drag and drop\n- Stored board state in Fireproof'
      });

      expect(result).toContain('react-beautiful-dnd');
      expect(result).toContain('Stored board state');
    });

    it('uses custom next steps', () => {
      const result = generateHandoff({
        nextSteps: 'User wants to add user authentication next'
      });

      expect(result).toContain('add user authentication');
    });

    it('uses custom VM name in commands', () => {
      const result = generateHandoff({
        vmName: 'customvm'
      });

      expect(result).toContain('customvm.exe.xyz');
      // Verify the default 'app' is not used (check for exact URL pattern)
      expect(result).not.toMatch(/open https:\/\/app\.exe\.xyz/);
    });

    it('combines all custom options', () => {
      const result = generateHandoff({
        appDescription: 'A recipe sharing app',
        files: ['index.html', 'recipes.json'],
        originalPrompt: 'Build a recipe app where I can save my favorite recipes',
        decisions: '- Used local storage via Fireproof\n- Added search functionality',
        nextSteps: 'Add image upload for recipes',
        vmName: 'recipes'
      });

      expect(result).toContain('A recipe sharing app');
      expect(result).toContain('`recipes.json`');
      expect(result).toContain('favorite recipes');
      expect(result).toContain('search functionality');
      expect(result).toContain('image upload');
      expect(result).toContain('recipes.exe.xyz');
    });
  });

  describe('output format', () => {
    it('includes generation timestamp', () => {
      const result = generateHandoff();
      const today = new Date().toISOString().split('T')[0];

      expect(result).toContain('Generated by vibes-skill on');
      expect(result).toContain(today);
    });

    it('includes common commands section', () => {
      const result = generateHandoff({ vmName: 'testapp' });

      expect(result).toContain('open https://testapp.exe.xyz');
      expect(result).toContain('nano /var/www/html/index.html');
      expect(result).toContain('sudo systemctl status nginx');
      expect(result).toContain('sudo tail -f /var/log/nginx/access.log');
    });

    it('describes the architecture', () => {
      const result = generateHandoff();

      expect(result).toContain('Single `index.html` file');
      expect(result).toContain('text/babel');
      expect(result).toContain('Import map');
      expect(result).toContain('esm.sh');
    });
  });
});

describe('extractContextFromEnv', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    // Reset environment before each test
    process.env = { ...originalEnv };
  });

  afterEach(() => {
    // Restore original environment
    process.env = originalEnv;
  });

  it('returns defaults when no env vars set', () => {
    delete process.env.VIBES_APP_DESCRIPTION;
    delete process.env.VIBES_ORIGINAL_PROMPT;
    delete process.env.VIBES_DECISIONS;
    delete process.env.VIBES_NEXT_STEPS;
    delete process.env.VIBES_VM_NAME;

    const context = extractContextFromEnv();

    expect(context.appDescription).toBe('A Vibes app');
    expect(context.originalPrompt).toBe('Build an app');
    expect(context.decisions).toContain('Standard Vibes architecture');
    expect(context.nextSteps).toContain('Continue development');
    expect(context.vmName).toBe('app');
  });

  it('reads VIBES_APP_DESCRIPTION', () => {
    process.env.VIBES_APP_DESCRIPTION = 'A custom todo app';

    const context = extractContextFromEnv();

    expect(context.appDescription).toBe('A custom todo app');
  });

  it('reads VIBES_ORIGINAL_PROMPT', () => {
    process.env.VIBES_ORIGINAL_PROMPT = 'Make me a shopping list app';

    const context = extractContextFromEnv();

    expect(context.originalPrompt).toBe('Make me a shopping list app');
  });

  it('reads VIBES_DECISIONS', () => {
    process.env.VIBES_DECISIONS = '- Added dark mode\n- Used local storage';

    const context = extractContextFromEnv();

    expect(context.decisions).toBe('- Added dark mode\n- Used local storage');
  });

  it('reads VIBES_NEXT_STEPS', () => {
    process.env.VIBES_NEXT_STEPS = 'User wants to add categories';

    const context = extractContextFromEnv();

    expect(context.nextSteps).toBe('User wants to add categories');
  });

  it('reads VIBES_VM_NAME', () => {
    process.env.VIBES_VM_NAME = 'myproject';

    const context = extractContextFromEnv();

    expect(context.vmName).toBe('myproject');
  });

  it('reads all env vars when set', () => {
    process.env.VIBES_APP_DESCRIPTION = 'Full stack app';
    process.env.VIBES_ORIGINAL_PROMPT = 'Build everything';
    process.env.VIBES_DECISIONS = 'Many decisions';
    process.env.VIBES_NEXT_STEPS = 'Next steps here';
    process.env.VIBES_VM_NAME = 'fullstack';

    const context = extractContextFromEnv();

    expect(context.appDescription).toBe('Full stack app');
    expect(context.originalPrompt).toBe('Build everything');
    expect(context.decisions).toBe('Many decisions');
    expect(context.nextSteps).toBe('Next steps here');
    expect(context.vmName).toBe('fullstack');
  });
});

describe('integration: generateHandoff with extractContextFromEnv', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    process.env = { ...originalEnv };
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  it('generates handoff from environment context', () => {
    process.env.VIBES_APP_DESCRIPTION = 'A notes app';
    process.env.VIBES_ORIGINAL_PROMPT = 'I need a place to store my notes';
    process.env.VIBES_VM_NAME = 'notes';

    const context = extractContextFromEnv();
    context.files = ['index.html'];

    const result = generateHandoff(context);

    expect(result).toContain('A notes app');
    expect(result).toContain('store my notes');
    expect(result).toContain('notes.exe.xyz');
  });
});
